run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/hellmai/lumenflow-example-go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
